spring:
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon_telecom
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true



management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    fall-back:
      registerHealthIndicator: true
      event-consumer-buffer-size: 10
      slidingWindowType: COUNT_BASED
      slidingWindowSize: 5
      waitDurationInOpenState: 30s # 30 seconds is the lockin period once the circuit is open
      failureRateThreshold: 50
      permittedNUmberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true


